### ISSUE TITLE
Coplanar points not in the nearest facet

### ISSUE THREAD

**Issue by plattfot** [qhull/qhull#35] opened 2019-01-30 19:40 UTC
Hi,
when running this command using qhull built from the v7.3.0 branch
```sh
 echo -e "3\n19\n0.40000000000000002 0.35999999999999999 1.0019424460431654\n0.40000000000000002 0.35999999999999999 1.0800000000000001\n0.40000000000000002 0.23999999999999994 1.0800000000000001\n0.40000000000000002 0.23999999999999999 1.0097122302158275\n0.40000000000000002 0.36000000000000004 1\n0.40000000000000002 0.23999999999999994 1\n0.41079136690647483 0.23999999999999994 1\n0.47999999999999998 0.24000000000000002 1\n0.47999999999999998 0.35999999999999999 1\n0.40215827338129495 0.36000000000000004 1\n0.36000000000000004 0.29999999999999999 0.95999999999999996\n0.36000000000000004 0.29999999999999999 1.0800000000000001\n0.47999999999999998 0.29999999999999999 1.0800000000000001\n0.48000000000000004 0.29999999999999999 0.95999999999999996\n0.35999999999999999 0.35999999999999999 0.95999999999999996\n0.35999999999999999 0.35999999999999999 1.0800000000000001\n0.47999999999999998 0.23999999999999999 1.0800000000000001\n0.47999999999999998 0.35999999999999999 0.95999999999999996\n0.47999999999999998 0.35999999999999999 1.0800000000000001" | qhull Qt Fc FP FI n
```

I noticed that the point 9 and 6 are not in the closest facet. 9 should be in facet 41 and not 40. 6 should be in 63 and not 62. Am I misinterpret the docs or is this a bug?

Thanks

**Comment by cbbarber** [comment] 2019-06-14 17:59
The problem is 'Qt'.   This option triangulates non-simplicial facets.   These facets are marked 'tricoplanar'  the hyperplane is shared between each of the facets and coplanar points are assigned to one.   There's no "closest" facet since all the hyperplanes are the same.  Qhull measure distance to hyperplanes.

For point 9 the non-simplicial facet is f12 (qhull Qc f)

- f12
    - flags: top tested
    - merges: 2
    - normal:         0        1        0
    - offset:      -0.36
    - center: 0.4159999999999999   0.36  1.032
    - coplanar set(furthest p4):
      p0:       0.4     0.36    1.002
      p9:    0.4022     0.36        1
      p1:       0.4     0.36     1.08
      p4:       0.4     0.36        1
      furthest distance= 5.6e-017
    - vertices: p18(v11) p15(v8) p17(v7) p14(v1)
    - neighboring facets: f22 f11 f7 f13
    - ridges:
     - r6 tested simplicialbot
           vertices: p15(v8) p14(v1)
           between f12 and f22
     - r11 tested simplicialtop simplicialbot
           vertices: p17(v7) p14(v1)
           between f11 and f12
     - r25 tested
           vertices: p18(v11) p17(v7)
           between f13 and f12
     - r24 tested
           vertices: p18(v11) p15(v8)
           between f12 and f7

It is triangulated into f40 and f41 (qhull Qc f Qt)

- f40
    - flags: top simplicial tricoplanar keepcentrum
    - owner of normal & centrum is facet f40
    - normal:         0        1        0
    - offset:      -0.36
    - center: 0.4159999999999999   0.36  1.032
    - coplanar set(furthest p4):
      p0:       0.4     0.36    1.002
      p9:    0.4022     0.36        1
      p1:       0.4     0.36     1.08
      p4:       0.4     0.36        1
      furthest distance= 5.6e-017
    - vertices: p18(v11) p15(v8) p14(v1)
    - neighboring facets: f53 f41 f45
- f41
    - flags: bottom simplicial tricoplanar
    - owner of normal & centrum is facet f40
    - normal:         0        1        0
    - offset:      -0.36
    - center: 0.4159999999999999   0.36  1.032
    - vertices: p18(v11) p17(v7) p14(v1)
    - neighboring facets: f36 f40 f58

For distance to vertices, use 'FP'.   It reports the same points whether or not 'Qt' is used (p5 for p6
 and p14 for p9)

(qhull FP)
14 9 12 0.05811471426835037
5 6 18 0.01079136690647481

(qhull FP Qt)
14 9 40 0.05811471426835037
5 6 62 0.01079136690647481

**Closed by cbbarber** 2019-06-14 17:59 UTC
