### ISSUE TITLE
qh.NOerrexit was not cleared before calling qh_initflags()

### ISSUE THREAD

**Issue by jhollowed** [qhull/qhull#56] opened 2020-01-30 23:00 UTC
I am using a third party package which calls qhull functions, when I get a seemingly opaque error:

QH6245 qhull internal error (qh_initflags): qh.NOerrexit was not cleared before calling qh_initflags().  It should be cleared after setjmp().  Exit qhull.

What does this mean? The package in question leads to this error on MacOS Mojave (but not on High Sierra)

**Comment by cbbarber** [comment] 2020-01-31 03:23
Please send the error to the Mojave developers.  It may indicate a serious problem.   Qhull uses setjmp for its error handling.   qh_errexit will fail badly if it is called when qh.NOerrexit is false and setjmp is not active.

                                        --Brad

At 06:00 PM 01/30/2020, Joe Hollowed wrote:

**Comment by jhollowed** [comment] 2020-01-31 14:12
> Please send the error to the Mojave developers. It may indicate a serious problem. Qhull uses setjmp for its error handling. qh_errexit will fail badly if it is called when qh.NOerrexit is false and setjmp is not active.

Bummer. I've sent a bug report to Apple. Are you sure this is purely a Mojave issue? Are there no cases of anyone successfully running qhull on Mojave?

**Comment by cbbarber** [comment] 2020-01-31 20:58
Qhull reported that the call to qjh_initflags did to meet its preconditions.   So the problem is in the caller.   I don't know how Mojave is using Qhull, or if Mojave is using some other package that includes Qhull.  If they use the C++ interface for Qhull, that may contribute to the problem.

You can turn on tracing to stderr with the T4 flag.  It will show the sequence of calls to qh_initflags.  My guess is that qh_initflags is getting called twice, perhaps after a previous error exit from Qhull.

                                --Brad

At 09:12 AM 01/31/2020, Joe Hollowed wrote:

**Comment by jhollowed** [comment] 2020-02-02 17:21
> Qhull reported that the call to qjh_initflags did to meet its preconditions. So the problem is in the caller. I don't know how Mojave is using Qhull, or if Mojave is using some other package that includes Qhull. If they use the C++ interface for Qhull, that may contribute to the problem. You can turn on tracing to stderr with the T4 flag. It will show the sequence of calls to qh_initflags. My guess is that qh_initflags is getting called twice, perhaps after a previous error exit from Qhull.


Sorry for any confusion, but it's not any Mojave internal function that is calling qhull, it's this tool:

https://github.com/steverangel/SDTFE

I certainly agree that the problem is the caller. It's just that the SDTFE code linked above, without any changes, works on High Sierra, yet raises this error on Mojave.

**Comment by cbbarber** [comment] 2020-05-07 16:06
Someone will need to review the Mojave interface to SDTFE and the SDTFE interface to Qhull.   It may be due to different initialization conventions between the two codes.  Or maybe Mojave is trying to reuse a previous instance of Qhull via SDTFE and not reinitializing correctly.

**Comment by cbbarber** [comment] 2021-06-22 20:06
No further discussion.   Closing.

**Closed by cbbarber** 2021-06-22 20:06 UTC
